export const EMAIL_ADDRESS = [
  '@qq.com',
  '@163.com',
  '@sina.com',
  '@sohu.com',
  '@sogou.com',
  '@tom.com',
  '@126.com',
  '@21cn.com'
]

export const ECHARTS_COLOR = ["#f3c1c6", "#f0f69f", "#b0e0a8", "#e41749", "#5bd1d7", "#348498", "#dedede"]

export const IMOOC_LOGIN_TOKEN = 'IMOOC-LOGIN-TOKEN'

export const CAREER_DIRECTION = [
  { id: 0, value: '全部' },
  { id: 1, value: '前端开发' },
  { id: 2, value: '后端开发' },
  { id: 3, value: '移动开发' },
  { id: 4, value: '算法&数学' },
  { id: 5, value: '前沿技术' },
  { id: 6, value: '云计算&大数据' },
  { id: 7, value: '运维&测试' },
  { id: 8, value: '数据库' },
  { id: 9, value: 'UI设计&多媒体' },
  { id: 10, value: '游戏' },
]

export const CLASSIFICATION = [
  { id: 0, value: '全部' },
  { id: 1, value: 'HTML/CSS' },
  { id: 2, value: 'JavaScript' },
  { id: 3, value: 'Vue.js' },
  { id: 4, value: 'React.JS' },
  { id: 5, value: 'Angular' },
  { id: 6, value: 'Node.js' },
  { id: 7, value: 'jQuery' },
  { id: 8, value: 'Bootstrap' },
  { id: 9, value: 'Sass/Less' },
  { id: 10, value: 'WebApp' },
  { id: 11, value: '小程序' },
  { id: 12, value: '前端工具' },
  { id: 13, value: 'Java' },
  { id: 14, value: 'SpringBoot' },
  { id: 15, value: 'Python' },
  { id: 16, value: '爬虫' },
  { id: 17, value: 'Django' },
  { id: 18, value: 'Tornado' },
  { id: 19, value: 'Go' },
  { id: 20, value: 'PHP' },
  { id: 21, value: 'C' },
  { id: 22, value: 'C++' },
  { id: 23, value: 'C#' },
  { id: 24, value: 'Ruby' },
  { id: 25, value: 'Android' },
  { id: 26, value: 'iOS' },
  { id: 27, value: 'React native' },
  { id: 28, value: 'WEEX' },
  { id: 29, value: '算法与数据结构' },
  { id: 30, value: '数学' },
  { id: 31, value: '大数据' },
  { id: 32, value: 'Hadoop' },
  { id: 33, value: 'Spark' },
  { id: 34, value: 'Hbase' },
  { id: 35, value: 'Storm' },
  { id: 36, value: '云计算' },
  { id: 37, value: 'AWS' },
  { id: 38, value: 'Docker' },
  { id: 39, value: 'Kubernetes' },
  { id: 40, value: '运维' },
  { id: 41, value: '自动化运维' },
  { id: 42, value: '运维工具' },
  { id: 43, value: 'Linux' },
  { id: 44, value: '测试' },
  { id: 45, value: '功能测试' },
  { id: 46, value: '性能测试' },
  { id: 47, value: '自动化测试' },
  { id: 48, value: '接口测试' },
  { id: 49, value: '安全测试' },
  { id: 50, value: 'MySQL' },
  { id: 51, value: 'Redis' },
  { id: 52, value: 'MongoDB' },
  { id: 53, value: 'Oracle' },
  { id: 54, value: 'SQL Server' },
  { id: 55, value: '微服务' },
  { id: 56, value: '区块链' },
  { id: 57, value: '模型制作' },
  { id: 58, value: '以太坊' },
  { id: 59, value: '人工智能' },
  { id: 60, value: '机器学习' },
  { id: 61, value: '深度学习' },
  { id: 62, value: '计算机视觉' },
  { id: 63, value: '自然语言处理' },
  { id: 64, value: '数据分析&挖掘' },
  { id: 65, value: '动效动画' },
  { id: 66, value: '设计基础' },
  { id: 67, value: '设计工具' },
  { id: 68, value: 'APPUI设计' },
  { id: 69, value: '产品交互' },
  { id: 70, value: 'Unity 3D' },
  { id: 71, value: 'CSS' },
  { id: 72, value: 'Cocos2d-x' },
  { id: 73, value: 'HTML5' },
  { id: 74, value: 'CSS3' },
  { id: 75, value: '算法' },
  { id: 76, value: 'NoSql' },
]

export const DIFFICULT = [
  { id: 0, value: '全部' },
  { id: 1, value: '入门' },
  { id: 2, value: '初级' },
  { id: 3, value: '高级' },
]

export const USER_TYPE = {
  101003: '管理员',
  101001: '普通用户',
  '管理员': 101003,
  '普通用户': 101001
}